### ISSUE TITLE
Crash with Gravity API [1.19]

### ISSUE THREAD

**Issue by Kubimate** [sf-inc/xp_storage#20] opened 2022-09-05 18:41 UTC
Crash at startup when Gravity API is present

`Mixin apply for mod xp_storage failed xpstorage.mixins.json:XpBottleItemMixin from mod xp_storage -> net.minecraft.class_1779: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1779::setXpAmountEntity with priority 1000 cannot inject into net/minecraft/class_1779::method_7836(Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1271; merged by com.fusionflux.gravity_api.mixin.ExperienceBottleItemMixin with priority 1000 [PREINJECT Applicator Phase -> xpstorage.mixins.json:XpBottleItemMixin from mod xp_storage -> Prepare Injections ->  -> localvar$zmn000$setXpAmountEntity(Lnet/minecraft/class_1683;Lnet/minecraft/class_1937;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;)Lnet/minecraft/class_1683; -> Prepare]`

[latest.log](https://github.com/sf-inc/xp_storage/files/9491618/latest.log)

**Comment by charlyb01** [comment] 2022-09-06 19:15
Hello, thanks for the report!
I checked the mod and actually, the issue doesn't come from my mod. The problem is that the API is overriding a function that already existed in Minecraft code while I was injecting code into it. I will tell Gravity API's maintainer to use a better way for this change so that it won't crash when playing with both mods. I will keep you updated if I get news from them ;)

**Comment by charlyb01** [comment] 2023-04-15 14:36
According to the other mod author, the issue is now fixed!

**Closed by charlyb01** 2023-04-15 14:36 UTC
Labels: wontfix

**Comment by Kubimate** [comment] 2023-04-16 07:58
Thanks!
