### ISSUE TITLE
Crash with Outvoted mod

### ISSUE THREAD

**Issue by How-Bout-No** [sf-inc/xp_storage#13] opened 2021-05-27 18:30 UTC
A user of mine reported a crash and found that it was because of this mod (https://github.com/How-Bout-No/Outvoted/issues/48).
After checking the crash log it looks to be XP Storage that's not playing nice, it seems to give the exact same error as reported in #12, and gives no pointers to any incompatibilities.

**Comment by charlyb01** [comment] 2021-05-27 19:24
Very new bug, that's weird. Seems to be only client side bug caused by Cardinal Component API. I'll check this during the weekend

**Comment by charlyb01** [comment] 2021-05-27 19:24
https://github.com/How-Bout-No/Outvoted/files/6556219/crash-2021-05-27_14.31.09-client.txt

**Comment by charlyb01** [comment] 2021-07-08 10:23
It should be fixed on the 1.17 version. If people still use this version, I will release an update but I'm not planning to update older versions for ever =)

**Closed by charlyb01** 2021-07-08 10:23 UTC
Labels: bug
